name: Run Selenium Tests on Merge to Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Chrome Docker image
        uses: docker/setup-docker@v3
        with:
          image: selenium/standalone-chrome

      - name: Run Selenium tests (within container)
        run: docker run selenium/standalone-chrome mvn test

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: mvn install

      - name: Run Selenium tests
        run:  mvn test -P login_test

        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
          SAUCE_URL: ${{ secrets.SAUCE_URL }}