name: Run Selenium Tests on Merge to Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'
          cache: maven

      - name: 'Install Chrome browser'
        run:
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f

      - name: Install dependencies
        run: mvn install

      - name: Run Selenium tests
        run:  mvn test -P login_test

        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
          SAUCE_URL: ${{ secrets.SAUCE_URL }}